load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "protocol",
    srcs = ["protocol.cpp"],
    hdrs = ["protocol.h"],
    deps = [
        "@glog//:glog",
    ],
)
