package(default_visibility = ["//visibility:public"])

filegroup(
    name = "goertzel_easy",
    srcs = [
        "easy.wav",
        "goertzel_easy_encoder_params.txt",
    ],
)

filegroup(
    name = "goertzel_medium",
    srcs = [
        "medium.wav",
        "goertzel_medium_encoder_params.txt",
    ],
)
