package(default_visibility = ["//visibility:public"])

filegroup(
    name = "goertzel_easy",
    srcs = [
        "easy.wav",
        "easy_encoder_params.txt",
    ],
)

filegroup(
    name = "goertzel_easy_noisy",
    srcs = [
        "easy_noisy.wav",
        "easy_noisy_encoder_params.txt",
    ],
)

filegroup(
    name = "goertzel_easy_noisy_plus",
    srcs = [
        "easy_noisy_plus.wav",
        "easy_noisy_plus_encoder_params.txt",
    ],
)

filegroup(
    name = "goertzel_medium",
    srcs = [
        "medium.wav",
        "medium_encoder_params.txt",
    ],
)
