package(default_visibility = ["//visibility:public"])

filegroup(
    name = "simple_encoder_sample",
    srcs = [
        "simple_encoder_sample.wav",
        "simple_encoder_sample_encoder_params.txt",
    ],
)
